# Generated by Django 2.2.6 on 2019-10-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='subtitle',
            field=models.CharField(default='', max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='text',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
