# Generated by Django 2.2.6 on 2019-12-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191024_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='image',
            field=models.ImageField(default='media/no-img.jpg', upload_to='media/'),
        ),
    ]
