# Generated by Django 2.2.6 on 2019-12-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_publicacao_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='image',
            field=models.ImageField(default='static/img/discussion.gif', upload_to='media/'),
        ),
    ]
