# Generated by Django 2.2.6 on 2019-12-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191210_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='image',
            field=models.ImageField(default='/discussion.gif', upload_to='media/'),
        ),
    ]
