# Generated by Django 2.2.6 on 2019-12-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191210_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='image',
            field=models.ImageField(default='/media/discussion.gif', null=True, upload_to='media/'),
        ),
    ]
